### ISSUE TITLE
他コンテンツへのナビゲーションメニューを追加

### ISSUE THREAD

**Issue by mktakuya** [yuru28/yuru28.github.io#42]
ヘッダかどこかにゆるふわノートへの導線を追加したい。

検索機能への導線も追加できるようにする。
https://github.com/yuru28/yuru28.github.io/issues/33

**Comment by toshiemon18** [comment]
https://yatteiki.fm
こんな感じにしたいね

**Comment by mktakuya** [comment]
## yatteiki.fm

![image](https://user-images.githubusercontent.com/2035364/67484895-f01c4f00-f6a3-11e9-9b11-ed3544b3ae31.png)


## Rebuild

![image](https://user-images.githubusercontent.com/2035364/67484911-fca0a780-f6a3-11e9-999e-8b7664527d76.png)


## backspace.fm

![image](https://user-images.githubusercontent.com/2035364/67484948-0e824a80-f6a4-11e9-9362-8b917edae6a0.png)
